server:
    servlet:
        context-path: /dmsApp
#     port: 8090
spring:
    main:
        banner-mode: off
        
logging.file: /dms/dmscustomapp/dmscomponentsapp.log
logging.file.max-history: 2

logging:
     pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n'
     level:
        hmrc.cds.dms: debug
        root: WARN


Environments:
    - DIT1
    - DIT2
    - DIT3
    - DIT4
    - FIT1
    - FIT2
    - FIT3
    - FIT4
    - Stress2
    
PDSURI: /DMSTraderService
XRSURI: /ExchangeRateService
TariffURI: /TariffManagementServiceSOAPHttp
ILMSURI: /AuthorizationsService
SPSURI: /bolt/securingpaymentservice
RDSURI: /ReferenceDataService
PDSHosts:
    - 'http://bolt-pds-dms-lb-1.delivery-team-cds-r1.n.cit.corp.hmrc.gov.uk:8000'
    - 'http://bolt-pds-dms-lb-1.delivery-team-cds-r2.n.cit.corp.hmrc.gov.uk:8000'
    - 'http://bolt-pds-dms-lb-1.delivery-team-cds-r3.n.cit.corp.hmrc.gov.uk:8000'
    - 'http://bolt-pds-dms-lb-1.delivery-team-nip-r4.d.cit.corp.hmrc.gov.uk:8000'
    - 'http://bolt-pds-dms-lb-1.core-env-cds-r1.n.cit.corp.hmrc.gov.uk:8000'
    - 'http://bolt-pds-dms-lb-1.core-env-cds-r2.n.cit.corp.hmrc.gov.uk:8000'
    - 'http://bolt-pds-dms-lb-1.core-env-cds-r3.n.cit.corp.hmrc.gov.uk:8000'
    - 'http://bolt-pds-dms-lb-1.core-env-cds-fin.n.cit.corp.hmrc.gov.uk:8000'
    - 'http://bolt-pds-dms-lb-1.delivery-team-dms-stress2.d.cit.corp.hmrc.gov.uk:8000'
    
XRSHosts:
    - 'http://bolt-xrs-lb-1.delivery-team-cds-r1.n.cit.corp.hmrc.gov.uk:8100'
    - 'http://bolt-xrs-lb-1.delivery-team-cds-r2.n.cit.corp.hmrc.gov.uk:8100'
    - 'http://bolt-xrs-lb-1.delivery-team-cds-r3.n.cit.corp.hmrc.gov.uk:8100'
    - 'http://bolt-xrs-lb-1.delivery-team-nip-r4.d.cit.corp.hmrc.gov.uk:8100'
    - 'http://bolt-xrs-lb-1.core-env-cds-r1.n.cit.corp.hmrc.gov.uk:8100'
    - 'http://bolt-xrs-lb-1.core-env-cds-r2.n.cit.corp.hmrc.gov.uk:8100'
    - 'http://bolt-xrs-lb-1.core-env-cds-r3.n.cit.corp.hmrc.gov.uk:8100'
    - 'http://bolt-xrs-lb-1.core-env-cds-fin.n.cit.corp.hmrc.gov.uk:8100'
    - 'http://bolt-xrs-lb-1.delivery-team-dms-stress2.d.cit.corp.hmrc.gov.uk:8100'
    
TariffHosts:
    - 'http://tycho-tmm-lb-1.delivery-team-cds-r1.n.cit.corp.hmrc.gov.uk'
    - 'http://tycho-tmm-lb-1.delivery-team-cds-r2.n.cit.corp.hmrc.gov.uk'
    - 'http://tycho-tmm-lb-1.delivery-team-cds-r3.n.cit.corp.hmrc.gov.uk'
    - 'http://tycho-tmm-lb-1.delivery-team-nip-r4.d.cit.corp.hmrc.gov.uk'
    - 'http://tycho-tmm-lb-1.core-env-cds-r1.n.cit.corp.hmrc.gov.uk'
    - 'http://tycho-tmm-lb-1.core-env-cds-r2.n.cit.corp.hmrc.gov.uk'
    - 'http://tycho-tmm-lb-1.core-env-cds-r3.n.cit.corp.hmrc.gov.uk'
    - 'http://tycho-tmm-lb-1.core-env-cds-r4.n.cit.corp.hmrc.gov.uk'
    - 'http://tycho-tmm-lb-1.delivery-team-dms-stress2.d.cit.corp.hmrc.gov.uk'
    
ILMSHosts:
    - 'http://bolt-auth-lb-1.delivery-team-cds-r1.n.cit.corp.hmrc.gov.uk:8110'
    - 'http://bolt-auth-lb-1.delivery-team-cds-r2.n.cit.corp.hmrc.gov.uk:8110'
    - 'http://bolt-auth-lb-1.delivery-team-cds-r3.n.cit.corp.hmrc.gov.uk:8110'
    - 'http://bolt-auth-lb-1.delivery-team-nip-r4.d.cit.corp.hmrc.gov.uk:8110'
    - 'http://bolt-auth-lb-1.core-env-cds-r1.n.cit.corp.hmrc.gov.uk:8110'
    - 'http://bolt-auth-lb-1.core-env-cds-r2.n.cit.corp.hmrc.gov.uk:8110'
    - 'http://bolt-auth-lb-1.core-env-cds-r3.n.cit.corp.hmrc.gov.uk:8110'
    - 'http://bolt-auth-lb-1.core-env-cds-fin.n.cit.corp.hmrc.gov.uk:8110'
    - 'http://bolt-auth-lb-1.delivery-team-dms-stress2.d.cit.corp.hmrc.gov.uk:8110'
    
SPSHosts:
    - 'http://bolt-sps-lb-1.delivery-team-cds-r1.n.cit.corp.hmrc.gov.uk:8030'
    - 'http://bolt-sps-lb-1.delivery-team-cds-r2.n.cit.corp.hmrc.gov.uk:8030'
    - 'http://bolt-sps-lb-1.delivery-team-cds-r3.n.cit.corp.hmrc.gov.uk:8030'
    - 'http://bolt-sps-lb-1.delivery-team-nip-r4.d.cit.corp.hmrc.gov.uk:8030'
    - 'http://bolt-sps-lb-1.core-env-cds-r1.n.cit.corp.hmrc.gov.uk:8030'
    - 'http://bolt-sps-lb-1.core-env-cds-r2.n.cit.corp.hmrc.gov.uk:8030'
    - 'http://bolt-sps-lb-1.core-env-cds-r3.n.cit.corp.hmrc.gov.uk:8030'
    - 'http://bolt-sps-lb-1.core-env-cds-fin.n.cit.corp.hmrc.gov.uk:8030'
    - 'http://bolt-sps-lb-1.delivery-team-dms-stress2.d.cit.corp.hmrc.gov.uk:8030'
RDSHosts:
    - 'http://bolt-rds-lb-1.delivery-team-cds-r1.n.cit.corp.hmrc.gov.uk:8020'
    - 'http://bolt-rds-lb-1.delivery-team-cds-r2.n.cit.corp.hmrc.gov.uk:8020'
    - 'http://bolt-rds-lb-1.delivery-team-cds-r3.n.cit.corp.hmrc.gov.uk:8020'
    - 'http://bolt-rds-lb-1.delivery-team-nip-r4.d.cit.corp.hmrc.gov.uk:8020'
    - 'http://bolt-rds-lb-1.core-env-cds-r1.n.cit.corp.hmrc.gov.uk:8020'
    - 'http://bolt-rds-lb-1.core-env-cds-r2.n.cit.corp.hmrc.gov.uk:8020'
    - 'http://bolt-rds-lb-1.core-env-cds-r3.n.cit.corp.hmrc.gov.uk:8020'
    - 'http://bolt-rds-lb-1.core-env-cds-fin.n.cit.corp.hmrc.gov.uk:8020'
    - 'http://bolt-rds-lb-1.delivery-team-dms-stress2.d.cit.corp.hmrc.gov.uk:8020'
    
ReportDestination: frfrfrf
SystemMapping:
    - PartyManagementServiceSOAP.wsdl: PDS
    - GuaranteeManagementServiceSOAP_v2.wsdl: SPS
    - AuthorizationManagementServiceSOAP_v2.wsdl: ILMS
    - ExchangeRateServiceSOAP.wsdl: XRS
    - ReferenceDataServiceSOAP.wsdl: RDS
    - TariffManagementServiceSOAP_v2.wsdl: Tariff


JMSEnvironments:
    - DIT1: 'dms-queue-manager-lb-1.delivery-team-cds-r1.n.cit.corp.hmrc.gov.uk'
    - DIT2: 'dms-queue-manager-lb-1.delivery-team-cds-r2.n.cit.corp.hmrc.gov.uk'
    - DIT3: 'dms-queue-manager-lb-1.delivery-team-cds-r3.n.cit.corp.hmrc.gov.uk'
    - DIT4: 'dms-queue-manager-lb-1.delivery-team-nip-r4.d.cit.corp.hmrc.gov.uk'
    - FIT1: 'dms-queue-manager-lb-1.core-env-cds-r1.n.cit.corp.hmrc.gov.uk'
    - FIT2: 'dms-queue-manager-lb-1.core-env-cds-r2.n.cit.corp.hmrc.gov.uk'
    - FIT3: 'dms-queue-manager-lb-1.core-env-cds-r3.n.cit.corp.hmrc.gov.uk'
    - FIT4: 'dms-queue-manager-lb-1.core-env-cds-fin.n.cit.corp.hmrc.gov.uk'
    - Stress2: 'dms-queue-manager-lb-1.delivery-team-dms-stress2.d.cit.corp.hmrc.gov.uk'
JMSQPORT : 1414
JMSQChannelName : 'DMSQM.SVRCONN'
    
ConfluenceURL: 'http://10.102.81.254:5558'    
ConfluenceUserName: '7898083'
ConfluencePwd: 'Syamala@2432'
ConfluencePageID: 51123443

