<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
                  name="ExternalPartyValidationServiceSOAP" 
                  targetNamespace="http://trade.core.ecf/ExternalPartyValidationServiceSOAP/v1/" 
                  xmlns:tns="http://trade.core.ecf/ExternalPartyValidationServiceSOAP/v1/" 
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <version>1.0</version>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="http://trade.core.ecf/ExternalPartyValidationServiceSOAP/v1/" xmlns:xsd_1="http://trade.core.ecf/messages/2017/03/31/">
      <xsd:import namespace="http://trade.core.ecf/messages/2017/03/31/" schemaLocation="messages_20170331/messages.xsd"/>
      <xsd:element name="validateDeclaration">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="declarationValidationRequest" type="xsd_1:DeclarationValidationRequest"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="validateDeclarationRequest">
    <wsdl:part element="tns:validateDeclaration" name="parameters"/>
  </wsdl:message>

  <wsdl:portType name="ExternalPartyValidationServiceSOAPJms">
    <wsdl:operation name="validateDeclaration">
      <wsdl:input message="tns:validateDeclarationRequest"/>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="ExternalPartyValidationBindingJms" type="tns:ExternalPartyValidationServiceSOAPJms">
    <soap:binding style="document" transport="http://www.w3.org/2010/soapjms/"/>
    <wsdl:operation name="validateDeclaration">
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="ExternalPartyValidationServiceSOAP">
    <wsdl:port binding="tns:ExternalPartyValidationBindingJms" name="ExternalPartyValidationPortJms">
      <soap:address location="jms:jndi:destinationName"/>
    </wsdl:port>
  </wsdl:service>  
  
</wsdl:definitions>
